# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180104_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default='', null=True, validators=[photos.validators.badwords_detector]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='license',
            field=models.CharField(choices=[(b'R1', 'Runner 1'), (b'R2', 'Runner 2')], max_length=3),
        ),
    ]
