# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 08:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.TextField(blank=True, default='', null=True, validators=[photos.validators.badwords_detector, django.core.validators.MinLengthValidator(100)]),
        ),
    ]
